### ISSUE TITLE
Globby dependency issue 

### ISSUE THREAD

**Issue by zprood** [canonical-web-and-design/cn.ubuntu.com#600]
## Summary

When testing the latest vanilla and dependency PR, it's failed while installing packages after yarn install v1.21.1

## Process

- Clone the latest code: git clone...
- Docker is running,
- Then execute: "./run"

## Screenshot
Errors are: 
```
error globby@12.0.2: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "12.14.0"
error Found incompatible module.
```
![image](https://user-images.githubusercontent.com/692206/150468738-9484740e-5d8b-4ad8-9b78-391c838857e0.png)

**Comment by anthonydillon** [comment]
This is due to your local node version being the old. You can change this using `nvm`. We recommend using the latest list version: v16.3.2.

We are moving away from using `./run` script to using the dotrun snap on Ubuntu or within mulyipass on a Mac. I would recommend trying to set this up. For more info: https://github.com/canonical-web-and-design/dotrun.

**Comment by zprood** [comment]
Hi Anthony, I tried to upgrade my local node to v16.x or v17, the error still existed. 
But I tried the latest dotrun guide with multipass, it works well. 
Never mind, I have moved to dotrun then.
